#ifndef _EXCLUDE_LIST_H
#define _EXCLUDE_LIST_H

//#define TIZEN_2_3_1
#define TIZEN_2_4

#define DEVICE_TYPE_MOBILE
//#define DEVICE_TYPE_WEARABLE

#define TBT_MODULE_BT
#define TBT_MODULE_APP_BT_OPP_CLIENT
#define TBT_MODULE_APP_BT_AUDIO_CONNECT
#define TBT_MODULE_APP_BT_HID_CONNECT
#define TBT_MODULE_APP_BT_HDP

#define TBT_MODULE_BLE
#define TBT_MODULE_BLE_GATT_CLIENT

#define TBT_MODULE_EFL
#define TBT_MODULE_APP_EFL_CALLBACK


#endif
